parameter_defaults:

    NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter', 'AggregateMultiTenancyIsolation', 'AggregateCoreFilter', 'AggregateRamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter', 'AggregateInstanceExtraSpecsFilter']
