parameter_defaults:
  # assign role capabilities Nova scheduler can match
  ComputeSchedulerHints:
    'capabilities:profile': 'compute'
  ComputeBSchedulerHints:
    'capabilities:profile': 'computeb'
  NovaComputeExtraConfig:
    nova::cpu_allocation_ratio: '16'
    nova::ram_allocation_ratio: '1.5'
  ComputeBExtraConfig:
    nova::cpu_allocation_ratio: '2'
    nova::ram_allocation_ratio: '1'
